### a correct request 1
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567812345678",
  "cardFromValidTill": "03/25",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### a correct request 2
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "1122334455667788",
  "cardFromValidTill": "12/27",
  "cardFromCVV": "A2M",
  "cardToNumber": "1234567812345678",
  "amount": {
    "value": 1000,
    "currency": "RUR"
  }
}

### a correct request 2 with inactive recipient
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "1122334455667788",
  "cardFromValidTill": "12/27",
  "cardFromCVV": "A2M",
  "cardToNumber": "8877665544332211",
  "amount": {
    "value": 1000,
    "currency": "RUR"
  }
}

### a correct request 2 with wrong card data
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "1122334455667788",
  "cardFromValidTill": "03/25",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### an incorrect request with shortened number
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "12345678123",
  "cardFromValidTill": "03/25",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### an incorrect request with empty number
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "",
  "cardFromValidTill": "03/25",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### an incorrect expired request
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567812345678",
  "cardFromValidTill": "06/19",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### a request for plain
POST http://localhost:5500/
Content-Type: application/json

{
  "cardFromNumber": "1234567812345678",
  "cardFromValidTill": "06/19",
  "cardFromCVV": "125",
  "cardToNumber": "8765432187654321",
  "amount": {
    "value": 100,
    "currency": "RUR"
  }
}

### totally wrong request
POST http://localhost:5500/transfer/transfer
Content-Type: application/json

{
  "value": "1234567812345678"
}


### confirmation request for #0
POST http://localhost:5500/transfer/confirmOperation
Content-Type: application/json

{
  "operationId": "0",
  "code": "0000"
}

### confirmation request for #1
POST http://localhost:5500/transfer/confirmOperation
Content-Type: application/json

{
  "operationId": "1",
  "code": "0000"
}

### confirmation request for #2
POST http://localhost:5500/transfer/confirmOperation
Content-Type: application/json

{
  "operationId": "2",
  "code": "0000"
}

