server:
  port: 5500

logging:
  level:
    org.springframework: INFO
    ru.netology: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: /log/cardwork.log

commission: 0.01