server:
  port: 5500

logging:
  level:
    org.springframework: INFO
    ru.netology: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./log/cardwork.log

application:
  commission: 0.01
#  front-url: "https://serp-ya.github.io"
  front-url: "http://localhost:3000"
